[2025-06-30T17:21:53.049+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-30T17:21:53.058+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_book_data manual__2025-06-30T17:16:46.898855+00:00 [queued]>
[2025-06-30T17:21:53.060+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.insert_book_data manual__2025-06-30T17:16:46.898855+00:00 [queued]>
[2025-06-30T17:21:53.060+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-30T17:21:53.065+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_book_data> on 2025-06-30 17:16:46.898855+00:00
[2025-06-30T17:21:53.068+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=205) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-30T17:21:53.069+0000] {standard_task_runner.py:63} INFO - Started process 207 to run task
[2025-06-30T17:21:53.069+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'insert_book_data', 'manual__2025-06-30T17:16:46.898855+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpdf5s0r76']
[2025-06-30T17:21:53.070+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask insert_book_data
[2025-06-30T17:21:53.095+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_store_amazon_books.insert_book_data manual__2025-06-30T17:16:46.898855+00:00 [running]> on host 714f151640e5
[2025-06-30T17:21:53.135+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='insert_book_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T17:16:46.898855+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-30T17:16:46.898855+00:00'
[2025-06-30T17:21:53.136+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-30T17:21:53.142+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-30T17:21:53.143+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/app.py", line 95, in insert_book_data_into_postgres
    raise ValueError("No book data found")
ValueError: No book data found
[2025-06-30T17:21:53.147+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fetch_and_store_amazon_books, task_id=insert_book_data, run_id=manual__2025-06-30T17:16:46.898855+00:00, execution_date=20250630T171646, start_date=20250630T172153, end_date=20250630T172153
[2025-06-30T17:21:53.151+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task insert_book_data (No book data found; 207)
[2025-06-30T17:21:53.170+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-30T17:21:53.177+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-30T17:21:53.177+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
