[2025-06-30T17:07:35.027+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-30T17:07:35.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.create_table manual__2025-06-30T16:23:04.482837+00:00 [queued]>
[2025-06-30T17:07:35.042+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_amazon_books.create_table manual__2025-06-30T16:23:04.482837+00:00 [queued]>
[2025-06-30T17:07:35.042+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-06-30T17:07:35.048+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table> on 2025-06-30 16:23:04.482837+00:00
[2025-06-30T17:07:35.057+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=56) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-30T17:07:35.058+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_amazon_books', 'create_table', 'manual__2025-06-30T16:23:04.482837+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmpfzsm5x5k']
[2025-06-30T17:07:35.058+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask create_table
[2025-06-30T17:07:35.058+0000] {standard_task_runner.py:63} INFO - Started process 65 to run task
[2025-06-30T17:07:35.090+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_and_store_amazon_books.create_table manual__2025-06-30T16:23:04.482837+00:00 [running]> on host a8cff8cf3ab7
[2025-06-30T17:07:35.153+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_amazon_books' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T16:23:04.482837+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-30T16:23:04.482837+00:00'
[2025-06-30T17:07:35.154+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-30T17:07:35.154+0000] {sql.py:276} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS books (
        id SERIAL PRIMARY KEY,
        title TEXT NOT NULL,
        authors TEXT,
        price TEXT,
        rating TEXT
    );
    
[2025-06-30T17:07:35.161+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-30T17:07:35.164+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `books_connection` isn't defined
[2025-06-30T17:07:35.194+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fetch_and_store_amazon_books, task_id=create_table, run_id=manual__2025-06-30T16:23:04.482837+00:00, execution_date=20250630T162304, start_date=20250630T170735, end_date=20250630T170735
[2025-06-30T17:07:35.203+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task create_table (The conn_id `books_connection` isn't defined; 65)
[2025-06-30T17:07:35.243+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-30T17:07:35.252+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-06-30T17:07:35.260+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-30T17:07:35.262+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
